# Generated by Django 4.1.3 on 2023-02-08 12:20

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/bg')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='portfolio/portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='portfolio/details')),
                ('image2', models.ImageField(upload_to='portfolio/details')),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('desc', ckeditor.fields.RichTextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_fk', to='portfoliodata.portfolio')),
            ],
        ),
    ]
