# Generated by Django 4.1.3 on 2023-02-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discount',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
